// src/components/projects/AIArchitecture.tsx
import MediumStyleProject from '../global/PageTemplate';

const AIArchitecture = () => {
  const projectData = {
    title: "AI Architecture",
    subtitle: "A StyleGAN-based exploration of architectural design using machine learning to generate and manipulate architectural spaces.",
    heroMedia: {
      type: 'video' as const,
      src: "https://portfolio-worthy.s3.amazonaws.com/flesh_digression.mp4",
    },
    githubUrl: "https://github.com/worthybrae/AI-Architecture",
    sections: [
      {
        title: "Introduction",
        content: "This project explores the intersection of artificial intelligence and architectural design, using StyleGAN technology to generate and transform architectural spaces. By training a neural network on a curated dataset of architectural images, I've created a system capable of generating novel architectural concepts and seamlessly morphing between different spatial configurations.",
      },
      {
        title: "Project Overview",
        content: "The AI Architecture project aimed to create a neural network capable of generating and manipulating architectural designs using StyleGAN technology. The key components included automated data collection, model training on architectural imagery, and implementation of various image manipulation techniques to create dynamic architectural transformations.",
        media: {
          type: 'image' as const,
          src: "https://portfolio-worthy.s3.amazonaws.com/generated-collage.png",
          caption: "Examples of architectural spaces generated by the trained StyleGAN model."
        }
      },
      {
        title: "Data Collection Process",
        content: "To train the StyleGAN model, I developed an automated web scraping system using Selenium WebDriver that collected high-quality architectural images from various online sources. The system included image processing with PIL for standardization, filtering for high-resolution images (minimum 512x512), and automatic cropping and resizing of images. This resulted in a dataset of 447 images across 578 scraped pages, all at a consistent resolution of 512x512 pixels.",
        media: {
          type: 'image' as const,
          src: "https://portfolio-worthy.s3.amazonaws.com/real-collage.jpg",
          caption: "A sample of the curated collection of high-quality architectural images used to train the StyleGAN model."
        }
      },
      {
        title: "Model Training",
        content: "The training process utilized StyleGAN2-ADA as the base model architecture. Training lasted approximately 24 hours with a batch size of 64 images at 256x256 resolution. Key parameters included a learning rate of 0.0002, beta values of [0, 0.99], and the ProjectedGANLoss loss function. Data augmentation was enabled to enhance model generalization despite the relatively small dataset size. This approach allowed the model to learn the underlying patterns and structures of architectural spaces while maintaining stability during training.",
        codeSnippet: {
          title: "Training Configuration",
          language: "python",
          code: `# StyleGAN2-ADA model configuration
config = {
    "batch_size": 64,
    "learning_rate": 0.0002,
    "betas": [0, 0.99],
    "loss_function": "ProjectedGANLoss",
    "augmentation": True,
    "resolution": 256,
    "channels": 3,
    "generator": {
        "z_dim": 512,
        "w_dim": 512,
        "mapping_layers": 8,
    }
}

# Start the training process
trainer = Trainer(config)
trainer.train(dataset, max_steps=25000)`
        }
      },
      {
        title: "The Flesh Digression Technique",
        content: "The most innovative aspect of this project is the implementation of what I call the 'flesh digression' technique, visible in the header video. This approach involves a novel method of latent space interpolation that creates organic transformations between different architectural styles. Unlike traditional linear interpolation, flesh digression follows curved paths through the latent space, resulting in more natural and visually intriguing transitions between generated architectural forms. This technique reveals the fluid nature of the model's learned representation of architectural space and form.",
      },
      {
        title: "Results & Impact",
        content: "The project successfully demonstrated the potential of StyleGAN in architectural design generation. Beyond technical achievement, this work explores important questions at the intersection of architecture, creativity, and artificial intelligence. The generated architectural spaces exist in a realm between human design and machine learning, challenging our understanding of architectural authorship. These AI-generated spaces offer a new perspective on design possibilities that wouldn't necessarily emerge from traditional architectural practice, potentially inspiring novel approaches to spatial composition and form generation."
      }
    ],
    relatedProjects: [
      {
        title: "Livestream Art",
        description: "Real-time artistic transformation of the iconic Abbey Road crossing livestream using computer vision and edge detection.",
        link: "/projects/livestream-art",
        image: "https://portfolio-worthy.s3.amazonaws.com/abbey-road-stream.mp4"
      },
      {
        title: "Country Density",
        description: "A data visualization project that transforms population density data into stunning 3D renderings.",
        link: "/projects/country-density",
        image: "https://portfolio-worthy.s3.us-east-1.amazonaws.com/density-preview.png"
      }
    ]
  };

  return <MediumStyleProject {...projectData} />;
};

export default AIArchitecture;